---
parser: babel-eslint

parserOptions:
  ecmaVersion: 8
  sourceType: "module"
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - airbnb

env:
  browser: true
  node: true

rules:
  no-mixed-operators:
    - error
    - groups: [["&", "|", "^", "~", "<<", ">>", ">>>"], ["&&", "||"]]
      allowSamePrecedence: true

plugins:
  - flowtype
  - flowtype-errors
  - import
  - promise
  - compat
  - react

settings:
  import/resolver:
    webpack:
      config: webpack.config.eslint.js
